config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :states
  resources :contacts
  resources :links
  resources :articles
  resources :officers
  resources :instruments

  mount Ckeditor::Engine => '/ckeditor'

  get 'tags/:tag', to: 'articles#index', as: :tag

  get '/about', to: 'pages#about', as: 'about'
  get '/officers_view', to: 'pages#officers', as: 'officers_view'
  get '/sot_award', to: 'pages#sot_award', as: 'sot_award'
  get '/photos', to: 'pages#photos', as: 'photos'
  get '/newsletters', to: 'pages#newsletters', as: 'newsletters'

  root 'pages#home'

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_one :officer

  def to_s
    title
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:title, :display_order, :email, :number_of_terms, :term_length)
    end
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <%= render partial: 'shared/errors', locals: { model: @office, model_name: 'office'} %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :display_order, class: 'control-label' %><br>
    <%= f.number_field :display_order, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'control-label' %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :term_limit, class: 'control-label' %><br>
    <%= f.number_field :term_limit, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :term_length, class: 'control-label' %><br>
    <%= f.number_field :term_length, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit nil,  {class: 'btn btn-default'} %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<%= title 'Offices' %>

<p id="notice"><%= notice %></p>

<h1>Listing Offices</h1>

<table class="data_table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Display order</th>
      <th>Email</th>
      <th>Term Limit</th>
      <th>Term Length</th>
      <th class="no-icon"></th>
      <th class="no-icon"></th>
      <th class="no-icon"></th>
    </tr>
    <tr>
      <td><input type='text' id='col1_filter' placeholder='filter' class='search_init'/></td>
      <td><input type='text' id='col2_filter' placeholder='filter' class='search_init'/></td>
      <td><input type='text' id='col3_filter' placeholder='filter' class='search_init'/></td>
      <td><input type='text' id='col4_filter' placeholder='filter' class='search_init'/></td>
      <td><input type='text' id='col5_filter' placeholder='filter' class='search_init'/></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.title %></td>
        <td><%= office.display_order %></td>
        <td><%= office.email %></td>
        <td><%= office.term_limit %></td>
        <td><%= office.term_length %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @office.title %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @office.display_order %>
</p>

<p>
  <strong>Email:</strong>
  <%= @office.email %>
</p>

<p>
  <strong>Term Limit:</strong>
  <%= @office.term_limit %>
</p>

<p>
  <strong>Term length:</strong>
  <%= @office.term_length %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>