config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :states
  resources :contacts
  resources :links
  resources :articles
  resources :officers
  resources :instruments

  mount Ckeditor::Engine => '/ckeditor'

  get 'tags/:tag', to: 'articles#index', as: :tag

  get '/about', to: 'pages#about', as: 'about'
  get '/officers_view', to: 'pages#officers', as: 'officers_view'
  get '/sot_award', to: 'pages#sot_award', as: 'sot_award'
  get '/photos', to: 'pages#photos', as: 'photos'
  get '/newsletters', to: 'pages#newsletters', as: 'newsletters'

  root 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_ordered_taggable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
    @articles = @articles.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    @tags = Article.tag_counts_on(:tags)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view
    @articles = Article.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author, :posting_date, :tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= render partial: 'shared/errors', locals: { model: @article, model_name: 'article'} %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body, class: 'control-label' %><br>
    <%= f.cktext_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, 'Tags', class: 'control-label' %><br>
    <%= f.text_field :tag_list, value: @article.tag_list.to_s, class: "form-control", id: "article_tags" %>
  </div>

  <div class="form-group">
    <%= f.label :author, class: 'control-label' %><br>
    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :posting_date, class: 'control-label' %><br>
    <%= f.datetime_select :posting_date, class: "datepicker" %>
  </div>

  <div class="actions">
    <%= f.submit nil,  {class: 'btn btn-default'} %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= content_for :content_layout, 'container-fluid' %>
<%= title 'Articles' %>

<div class="row">
  <div class="col-sm-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Tags</h3>
      </div>
      <div class="panel-body">
        <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
          <%= link_to tag.name, { action: :index, tag: tag.name }, class: css_class %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-10">
    <% @articles.each do |article| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= article.title %></h3>
        </div>
        <div class="panel-body">
          <%= get_html(article.body) %>
          <div class="article-footer">
            Posted
            <% if article.author %> by <%= article.author %><% end %>
            <%= time_ago_in_words article.created_at %> ago
          </div>
        </div>
      </div>
    <% end %>
    <div class="flickr_pagination">
      <%= will_paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= get_html(@article.body) %>
</p>

<p>
  <strong>Tags:</strong>
  <%= raw @article.tag_list.map { |t| link_to(t, tag_path(t)) }.join(', ') %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Posting date:</strong>
  <%= @article.posting_date %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/view.html.erb
<%= content_for :content_layout, 'main-content-large' %>

<div class="left">
  <% @articles.each do |article| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= article.title %></h3>
      </div>
      <div class="panel-body">
        <%= article.body %>
      </div>
    </div>
  <% end %>
</div>

<div class="right">
  <a class="twitter-timeline" href="https://twitter.com/SpiritOfTech" data-widget-id="701410603756290048">Tweets by @SpiritOfTech</a>
  <br/><br/>
  <div class="fb-page" data-href="https://www.facebook.com/MarchingVirginians/" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
    <div class="fb-xfbml-parse-ignore">
      <blockquote cite="https://www.facebook.com/MarchingVirginians/">
        <a href="https://www.facebook.com/MarchingVirginians/">The Marching Virginians - The Spirit of Tech</a>
      </blockquote>
    </div>
  </div>
</div>

<div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=1536424336583139";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<script>
  (function(d,s,id){
    var js, fjs=d.getElementsByTagName(s)[0];
    var p = /^http:/.test(d.location) ? 'http' : 'https';
    if(!d.getElementById(id)){
      js = d.createElement(s);
      js.id = id;
      js.src = p+"://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js,fjs);
    }
  }(document,"script","twitter-wjs"));
</script>