config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :states
  resources :contacts
  resources :links
  resources :articles
  resources :officers
  resources :instruments

  mount Ckeditor::Engine => '/ckeditor'

  get 'tags/:tag', to: 'articles#index', as: :tag

  get '/about', to: 'pages#about', as: 'about'
  get '/officers_view', to: 'pages#officers', as: 'officers_view'
  get '/sot_award', to: 'pages#sot_award', as: 'sot_award'
  get '/photos', to: 'pages#photos', as: 'photos'
  get '/newsletters', to: 'pages#newsletters', as: 'newsletters'

  root 'pages#home'

end

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model_name %> from being saved:</h2>

    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="col-sm-4 text-left">
      Contact
    </div>
    <div class="col-sm-4 text-center">
      <a href="#"><i class="fa fa-facebook-official social-icon facebook"></i></a>
      <a href="#"><i class="fa fa-twitter social-icon twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin social-icon linked-in"></i></a>
    </div>
    <div class="col-sm-4 text-right">
      <% if Link.count > 0 %>
        <ul>Links
          <% Link.all.each do |link| %>
            <li><%= link_to link.title, link.url %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MVAA', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= cp(root_path) %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= cp(about_path) %>"><%= link_to "About", about_path %></li>
        <li class="<%= cp(officers_view_path) %>"><%= link_to "Officers", officers_view_path %></li>
        <li class="<%= cp(photos_path) %>"><%= link_to "Photos", photos_path %></li>
        <li class="<%= cp(newsletters_path) %>"><%= link_to "Newsletters", newsletters_path %></li>
        <li class="<%= cp(sot_award_path) %>"><%= link_to "SoT Award", sot_award_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= cp(articles_path) %>"><%= link_to "Articles", articles_path %></li>
            <li class="<%= cp(contacts_path) %>"><%= link_to "Contacts", contacts_path %></li>
            <li class="<%= cp(instruments_path) %>"><%= link_to "Instruments", instruments_path %></li>
            <li class="<%= cp(links_path) %>"><%= link_to "Links", links_path %></li>
            <li class="<%= cp(offices_path) %>"><%= link_to "Offices", offices_path %></li>
            <li class="<%= cp(officers_path) %>"><%= link_to "Officers", officers_path %></li>
            <li class="<%= cp(states_path) %>"><%= link_to "States", states_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" action="http://groups.google.com/group/mvaa/boxsubscribe">
        <div class="form-group">
          <input type=text class="form-control" name="email" placeholder="Email">
        </div>
        <button type="submit" name="sub" class="btn btn-primary">Subscribe to Google Group</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>