config/routes.rb
Rails.application.routes.draw do
  resources :offices
  resources :states
  resources :contacts
  resources :links
  resources :articles
  resources :officers
  resources :instruments

  mount Ckeditor::Engine => '/ckeditor'

  get 'tags/:tag', to: 'articles#index', as: :tag

  get '/about', to: 'pages#about', as: 'about'
  get '/officers_view', to: 'pages#officers', as: 'officers_view'
  get '/sot_award', to: 'pages#sot_award', as: 'sot_award'
  get '/photos', to: 'pages#photos', as: 'photos'
  get '/newsletters', to: 'pages#newsletters', as: 'newsletters'

  root 'pages#home'

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :officers
  has_many :contacts

  def to_s
    name
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:name)
    end
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <%= render partial: 'shared/errors', locals: { model: @instrument, model_name: 'instrument'} %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label' %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit nil,  {class: 'btn btn-default'} %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing Instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<%= title 'Instruments' %>

<p id="notice"><%= notice %></p>

<h1>Listing Instruments</h1>

<table class="data_table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="no-icon"></th>
      <th class="no-icon"></th>
      <th class="no-icon"></th>
    </tr>
    <tr>
      <td><input type='text' id='col1_filter' placeholder='filter' class='search_init'/></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.name %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New Instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instrument.name %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>